//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.26 at 01:01:09 PM GMT 
//


package walla.datatypes.auto;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="ProfileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AccountType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AccountCondition" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StorageGB" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="CurrentGB" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ImageCount" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="Machines">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Machine" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}long" default="0" />
 *                           &lt;attribute name="platformId" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="lastUsed" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                           &lt;attribute name="tagId" type="{http://www.w3.org/2001/XMLSchema}long" default="0" />
 *                           &lt;attribute name="categoryId" type="{http://www.w3.org/2001/XMLSchema}long" default="0" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}long" default="0" />
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "profileName",
    "email",
    "password",
    "description",
    "accountType",
    "accountCondition",
    "storageGB",
    "currentGB",
    "imageCount",
    "machines"
})
@XmlRootElement(name = "Account", namespace = "http://www.example.org/Account")
public class Account {

    @XmlElement(name = "ProfileName", namespace = "http://www.example.org/Account")
    protected String profileName;
    @XmlElement(name = "Email", namespace = "http://www.example.org/Account")
    protected String email;
    @XmlElement(name = "Password", namespace = "http://www.example.org/Account")
    protected String password;
    @XmlElement(name = "Description", namespace = "http://www.example.org/Account")
    protected String description;
    @XmlElement(name = "AccountType", namespace = "http://www.example.org/Account")
    protected String accountType;
    @XmlElement(name = "AccountCondition", namespace = "http://www.example.org/Account")
    protected String accountCondition;
    @XmlElement(name = "StorageGB", namespace = "http://www.example.org/Account")
    protected Integer storageGB;
    @XmlElement(name = "CurrentGB", namespace = "http://www.example.org/Account")
    protected Integer currentGB;
    @XmlElement(name = "ImageCount", namespace = "http://www.example.org/Account")
    protected Long imageCount;
    @XmlElement(name = "Machines", namespace = "http://www.example.org/Account")
    protected Account.Machines machines;
    @XmlAttribute(name = "id")
    protected Long id;
    @XmlAttribute(name = "version")
    protected Integer version;

    /**
     * Gets the value of the profileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfileName() {
        return profileName;
    }

    /**
     * Sets the value of the profileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfileName(String value) {
        this.profileName = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the accountType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * Sets the value of the accountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountType(String value) {
        this.accountType = value;
    }

    /**
     * Gets the value of the accountCondition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountCondition() {
        return accountCondition;
    }

    /**
     * Sets the value of the accountCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountCondition(String value) {
        this.accountCondition = value;
    }

    /**
     * Gets the value of the storageGB property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStorageGB() {
        return storageGB;
    }

    /**
     * Sets the value of the storageGB property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStorageGB(Integer value) {
        this.storageGB = value;
    }

    /**
     * Gets the value of the currentGB property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCurrentGB() {
        return currentGB;
    }

    /**
     * Sets the value of the currentGB property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCurrentGB(Integer value) {
        this.currentGB = value;
    }

    /**
     * Gets the value of the imageCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getImageCount() {
        return imageCount;
    }

    /**
     * Sets the value of the imageCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setImageCount(Long value) {
        this.imageCount = value;
    }

    /**
     * Gets the value of the machines property.
     * 
     * @return
     *     possible object is
     *     {@link Account.Machines }
     *     
     */
    public Account.Machines getMachines() {
        return machines;
    }

    /**
     * Sets the value of the machines property.
     * 
     * @param value
     *     allowed object is
     *     {@link Account.Machines }
     *     
     */
    public void setMachines(Account.Machines value) {
        this.machines = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public long getId() {
        if (id == null) {
            return  0L;
        } else {
            return id;
        }
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getVersion() {
        if (version == null) {
            return  0;
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVersion(Integer value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Machine" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}long" default="0" />
     *                 &lt;attribute name="platformId" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="lastUsed" type="{http://www.w3.org/2001/XMLSchema}date" />
     *                 &lt;attribute name="tagId" type="{http://www.w3.org/2001/XMLSchema}long" default="0" />
     *                 &lt;attribute name="categoryId" type="{http://www.w3.org/2001/XMLSchema}long" default="0" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "machine"
    })
    public static class Machines {

        @XmlElement(name = "Machine", namespace = "http://www.example.org/Account")
        protected List<Account.Machines.Machine> machine;

        /**
         * Gets the value of the machine property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the machine property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMachine().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Account.Machines.Machine }
         * 
         * 
         */
        public List<Account.Machines.Machine> getMachine() {
            if (machine == null) {
                machine = new ArrayList<Account.Machines.Machine>();
            }
            return this.machine;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}long" default="0" />
         *       &lt;attribute name="platformId" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="lastUsed" type="{http://www.w3.org/2001/XMLSchema}date" />
         *       &lt;attribute name="tagId" type="{http://www.w3.org/2001/XMLSchema}long" default="0" />
         *       &lt;attribute name="categoryId" type="{http://www.w3.org/2001/XMLSchema}long" default="0" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Machine {

            @XmlAttribute(name = "id")
            protected Long id;
            @XmlAttribute(name = "platformId")
            protected Integer platformId;
            @XmlAttribute(name = "name")
            protected String name;
            @XmlAttribute(name = "lastUsed")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar lastUsed;
            @XmlAttribute(name = "tagId")
            protected Long tagId;
            @XmlAttribute(name = "categoryId")
            protected Long categoryId;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public long getId() {
                if (id == null) {
                    return  0L;
                } else {
                    return id;
                }
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setId(Long value) {
                this.id = value;
            }

            /**
             * Gets the value of the platformId property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getPlatformId() {
                return platformId;
            }

            /**
             * Sets the value of the platformId property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setPlatformId(Integer value) {
                this.platformId = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the lastUsed property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getLastUsed() {
                return lastUsed;
            }

            /**
             * Sets the value of the lastUsed property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setLastUsed(XMLGregorianCalendar value) {
                this.lastUsed = value;
            }

            /**
             * Gets the value of the tagId property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public long getTagId() {
                if (tagId == null) {
                    return  0L;
                } else {
                    return tagId;
                }
            }

            /**
             * Sets the value of the tagId property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setTagId(Long value) {
                this.tagId = value;
            }

            /**
             * Gets the value of the categoryId property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public long getCategoryId() {
                if (categoryId == null) {
                    return  0L;
                } else {
                    return categoryId;
                }
            }

            /**
             * Sets the value of the categoryId property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setCategoryId(Long value) {
                this.categoryId = value;
            }

        }

    }

}
