//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.11 at 03:01:33 PM GMT 
//


package walla.datatypes.auto;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Desc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UrlComplex" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AccessType" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SelectionType" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="GroupingType" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="StyleId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="PresentationId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="TotalImageCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="LastChanged" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="ShowGalleryName" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="ShowGalleryDesc" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="ShowImageName" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="ShowImageDesc" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="ShowImageMeta" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Users">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="UserRef" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="emailAddress" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Categories">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CategoryRef" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="categoryId" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                           &lt;attribute name="recursive" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Tags">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TagRef" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="tagId" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                           &lt;attribute name="exclude" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Sorts">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SortRef" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="fieldname" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="ascending" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Sections">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SectionRef" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="sectionId" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                           &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Desc" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="imageCount" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "desc",
    "urlComplex",
    "accessType",
    "password",
    "selectionType",
    "groupingType",
    "styleId",
    "presentationId",
    "totalImageCount",
    "lastChanged",
    "showGalleryName",
    "showGalleryDesc",
    "showImageName",
    "showImageDesc",
    "showImageMeta",
    "users",
    "categories",
    "tags",
    "sorts",
    "sections"
})
@XmlRootElement(name = "Gallery", namespace = "http://www.example.org/Gallery")
public class Gallery {

    @XmlElement(name = "Name", namespace = "http://www.example.org/Gallery")
    protected String name;
    @XmlElement(name = "Desc", namespace = "http://www.example.org/Gallery")
    protected String desc;
    @XmlElement(name = "UrlComplex", namespace = "http://www.example.org/Gallery")
    protected String urlComplex;
    @XmlElement(name = "AccessType", namespace = "http://www.example.org/Gallery")
    protected Integer accessType;
    @XmlElement(name = "Password", namespace = "http://www.example.org/Gallery")
    protected String password;
    @XmlElement(name = "SelectionType", namespace = "http://www.example.org/Gallery")
    protected Integer selectionType;
    @XmlElement(name = "GroupingType", namespace = "http://www.example.org/Gallery")
    protected Integer groupingType;
    @XmlElement(name = "StyleId", namespace = "http://www.example.org/Gallery")
    protected Integer styleId;
    @XmlElement(name = "PresentationId", namespace = "http://www.example.org/Gallery")
    protected Integer presentationId;
    @XmlElement(name = "TotalImageCount", namespace = "http://www.example.org/Gallery")
    protected Integer totalImageCount;
    @XmlElement(name = "LastChanged", namespace = "http://www.example.org/Gallery")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastChanged;
    @XmlElement(name = "ShowGalleryName", namespace = "http://www.example.org/Gallery")
    protected Boolean showGalleryName;
    @XmlElement(name = "ShowGalleryDesc", namespace = "http://www.example.org/Gallery")
    protected Boolean showGalleryDesc;
    @XmlElement(name = "ShowImageName", namespace = "http://www.example.org/Gallery")
    protected Boolean showImageName;
    @XmlElement(name = "ShowImageDesc", namespace = "http://www.example.org/Gallery")
    protected Boolean showImageDesc;
    @XmlElement(name = "ShowImageMeta", namespace = "http://www.example.org/Gallery")
    protected Boolean showImageMeta;
    @XmlElement(name = "Users", namespace = "http://www.example.org/Gallery")
    protected Gallery.Users users;
    @XmlElement(name = "Categories", namespace = "http://www.example.org/Gallery")
    protected Gallery.Categories categories;
    @XmlElement(name = "Tags", namespace = "http://www.example.org/Gallery")
    protected Gallery.Tags tags;
    @XmlElement(name = "Sorts", namespace = "http://www.example.org/Gallery")
    protected Gallery.Sorts sorts;
    @XmlElement(name = "Sections", namespace = "http://www.example.org/Gallery")
    protected Gallery.Sections sections;
    @XmlAttribute(name = "id")
    protected Long id;
    @XmlAttribute(name = "version")
    protected Integer version;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesc() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesc(String value) {
        this.desc = value;
    }

    /**
     * Gets the value of the urlComplex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrlComplex() {
        return urlComplex;
    }

    /**
     * Sets the value of the urlComplex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrlComplex(String value) {
        this.urlComplex = value;
    }

    /**
     * Gets the value of the accessType property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAccessType() {
        return accessType;
    }

    /**
     * Sets the value of the accessType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAccessType(Integer value) {
        this.accessType = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the selectionType property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSelectionType() {
        return selectionType;
    }

    /**
     * Sets the value of the selectionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSelectionType(Integer value) {
        this.selectionType = value;
    }

    /**
     * Gets the value of the groupingType property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGroupingType() {
        return groupingType;
    }

    /**
     * Sets the value of the groupingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGroupingType(Integer value) {
        this.groupingType = value;
    }

    /**
     * Gets the value of the styleId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStyleId() {
        return styleId;
    }

    /**
     * Sets the value of the styleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStyleId(Integer value) {
        this.styleId = value;
    }

    /**
     * Gets the value of the presentationId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPresentationId() {
        return presentationId;
    }

    /**
     * Sets the value of the presentationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPresentationId(Integer value) {
        this.presentationId = value;
    }

    /**
     * Gets the value of the totalImageCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalImageCount() {
        return totalImageCount;
    }

    /**
     * Sets the value of the totalImageCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalImageCount(Integer value) {
        this.totalImageCount = value;
    }

    /**
     * Gets the value of the lastChanged property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastChanged() {
        return lastChanged;
    }

    /**
     * Sets the value of the lastChanged property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastChanged(XMLGregorianCalendar value) {
        this.lastChanged = value;
    }

    /**
     * Gets the value of the showGalleryName property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowGalleryName() {
        return showGalleryName;
    }

    /**
     * Sets the value of the showGalleryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowGalleryName(Boolean value) {
        this.showGalleryName = value;
    }

    /**
     * Gets the value of the showGalleryDesc property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowGalleryDesc() {
        return showGalleryDesc;
    }

    /**
     * Sets the value of the showGalleryDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowGalleryDesc(Boolean value) {
        this.showGalleryDesc = value;
    }

    /**
     * Gets the value of the showImageName property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowImageName() {
        return showImageName;
    }

    /**
     * Sets the value of the showImageName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowImageName(Boolean value) {
        this.showImageName = value;
    }

    /**
     * Gets the value of the showImageDesc property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowImageDesc() {
        return showImageDesc;
    }

    /**
     * Sets the value of the showImageDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowImageDesc(Boolean value) {
        this.showImageDesc = value;
    }

    /**
     * Gets the value of the showImageMeta property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowImageMeta() {
        return showImageMeta;
    }

    /**
     * Sets the value of the showImageMeta property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowImageMeta(Boolean value) {
        this.showImageMeta = value;
    }

    /**
     * Gets the value of the users property.
     * 
     * @return
     *     possible object is
     *     {@link Gallery.Users }
     *     
     */
    public Gallery.Users getUsers() {
        return users;
    }

    /**
     * Sets the value of the users property.
     * 
     * @param value
     *     allowed object is
     *     {@link Gallery.Users }
     *     
     */
    public void setUsers(Gallery.Users value) {
        this.users = value;
    }

    /**
     * Gets the value of the categories property.
     * 
     * @return
     *     possible object is
     *     {@link Gallery.Categories }
     *     
     */
    public Gallery.Categories getCategories() {
        return categories;
    }

    /**
     * Sets the value of the categories property.
     * 
     * @param value
     *     allowed object is
     *     {@link Gallery.Categories }
     *     
     */
    public void setCategories(Gallery.Categories value) {
        this.categories = value;
    }

    /**
     * Gets the value of the tags property.
     * 
     * @return
     *     possible object is
     *     {@link Gallery.Tags }
     *     
     */
    public Gallery.Tags getTags() {
        return tags;
    }

    /**
     * Sets the value of the tags property.
     * 
     * @param value
     *     allowed object is
     *     {@link Gallery.Tags }
     *     
     */
    public void setTags(Gallery.Tags value) {
        this.tags = value;
    }

    /**
     * Gets the value of the sorts property.
     * 
     * @return
     *     possible object is
     *     {@link Gallery.Sorts }
     *     
     */
    public Gallery.Sorts getSorts() {
        return sorts;
    }

    /**
     * Sets the value of the sorts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Gallery.Sorts }
     *     
     */
    public void setSorts(Gallery.Sorts value) {
        this.sorts = value;
    }

    /**
     * Gets the value of the sections property.
     * 
     * @return
     *     possible object is
     *     {@link Gallery.Sections }
     *     
     */
    public Gallery.Sections getSections() {
        return sections;
    }

    /**
     * Sets the value of the sections property.
     * 
     * @param value
     *     allowed object is
     *     {@link Gallery.Sections }
     *     
     */
    public void setSections(Gallery.Sections value) {
        this.sections = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVersion(Integer value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CategoryRef" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="categoryId" type="{http://www.w3.org/2001/XMLSchema}long" />
     *                 &lt;attribute name="recursive" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "categoryRef"
    })
    public static class Categories {

        @XmlElement(name = "CategoryRef", namespace = "http://www.example.org/Gallery")
        protected List<Gallery.Categories.CategoryRef> categoryRef;

        /**
         * Gets the value of the categoryRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the categoryRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCategoryRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Gallery.Categories.CategoryRef }
         * 
         * 
         */
        public List<Gallery.Categories.CategoryRef> getCategoryRef() {
            if (categoryRef == null) {
                categoryRef = new ArrayList<Gallery.Categories.CategoryRef>();
            }
            return this.categoryRef;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="categoryId" type="{http://www.w3.org/2001/XMLSchema}long" />
         *       &lt;attribute name="recursive" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class CategoryRef {

            @XmlAttribute(name = "categoryId")
            protected Long categoryId;
            @XmlAttribute(name = "recursive")
            protected Boolean recursive;

            /**
             * Gets the value of the categoryId property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getCategoryId() {
                return categoryId;
            }

            /**
             * Sets the value of the categoryId property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setCategoryId(Long value) {
                this.categoryId = value;
            }

            /**
             * Gets the value of the recursive property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isRecursive() {
                return recursive;
            }

            /**
             * Sets the value of the recursive property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setRecursive(Boolean value) {
                this.recursive = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SectionRef" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="sectionId" type="{http://www.w3.org/2001/XMLSchema}long" />
     *                 &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="Desc" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="imageCount" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sectionRef"
    })
    public static class Sections {

        @XmlElement(name = "SectionRef", namespace = "http://www.example.org/Gallery")
        protected List<Gallery.Sections.SectionRef> sectionRef;

        /**
         * Gets the value of the sectionRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the sectionRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSectionRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Gallery.Sections.SectionRef }
         * 
         * 
         */
        public List<Gallery.Sections.SectionRef> getSectionRef() {
            if (sectionRef == null) {
                sectionRef = new ArrayList<Gallery.Sections.SectionRef>();
            }
            return this.sectionRef;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="sectionId" type="{http://www.w3.org/2001/XMLSchema}long" />
         *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="Desc" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="imageCount" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class SectionRef {

            @XmlAttribute(name = "sectionId")
            protected Long sectionId;
            @XmlAttribute(name = "Name")
            protected String name;
            @XmlAttribute(name = "Desc")
            protected String desc;
            @XmlAttribute(name = "imageCount")
            protected Integer imageCount;

            /**
             * Gets the value of the sectionId property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getSectionId() {
                return sectionId;
            }

            /**
             * Sets the value of the sectionId property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setSectionId(Long value) {
                this.sectionId = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the desc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDesc() {
                return desc;
            }

            /**
             * Sets the value of the desc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDesc(String value) {
                this.desc = value;
            }

            /**
             * Gets the value of the imageCount property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getImageCount() {
                return imageCount;
            }

            /**
             * Sets the value of the imageCount property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setImageCount(Integer value) {
                this.imageCount = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SortRef" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="fieldname" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="ascending" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sortRef"
    })
    public static class Sorts {

        @XmlElement(name = "SortRef", namespace = "http://www.example.org/Gallery")
        protected List<Gallery.Sorts.SortRef> sortRef;

        /**
         * Gets the value of the sortRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the sortRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSortRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Gallery.Sorts.SortRef }
         * 
         * 
         */
        public List<Gallery.Sorts.SortRef> getSortRef() {
            if (sortRef == null) {
                sortRef = new ArrayList<Gallery.Sorts.SortRef>();
            }
            return this.sortRef;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="fieldname" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="ascending" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class SortRef {

            @XmlAttribute(name = "fieldname")
            protected String fieldname;
            @XmlAttribute(name = "ascending")
            protected Boolean ascending;

            /**
             * Gets the value of the fieldname property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFieldname() {
                return fieldname;
            }

            /**
             * Sets the value of the fieldname property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFieldname(String value) {
                this.fieldname = value;
            }

            /**
             * Gets the value of the ascending property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isAscending() {
                return ascending;
            }

            /**
             * Sets the value of the ascending property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setAscending(Boolean value) {
                this.ascending = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TagRef" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="tagId" type="{http://www.w3.org/2001/XMLSchema}long" />
     *                 &lt;attribute name="exclude" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tagRef"
    })
    public static class Tags {

        @XmlElement(name = "TagRef", namespace = "http://www.example.org/Gallery")
        protected List<Gallery.Tags.TagRef> tagRef;

        /**
         * Gets the value of the tagRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the tagRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTagRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Gallery.Tags.TagRef }
         * 
         * 
         */
        public List<Gallery.Tags.TagRef> getTagRef() {
            if (tagRef == null) {
                tagRef = new ArrayList<Gallery.Tags.TagRef>();
            }
            return this.tagRef;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="tagId" type="{http://www.w3.org/2001/XMLSchema}long" />
         *       &lt;attribute name="exclude" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class TagRef {

            @XmlAttribute(name = "tagId")
            protected Long tagId;
            @XmlAttribute(name = "exclude")
            protected Boolean exclude;

            /**
             * Gets the value of the tagId property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getTagId() {
                return tagId;
            }

            /**
             * Sets the value of the tagId property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setTagId(Long value) {
                this.tagId = value;
            }

            /**
             * Gets the value of the exclude property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isExclude() {
                return exclude;
            }

            /**
             * Sets the value of the exclude property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setExclude(Boolean value) {
                this.exclude = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="UserRef" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="emailAddress" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "userRef"
    })
    public static class Users {

        @XmlElement(name = "UserRef", namespace = "http://www.example.org/Gallery")
        protected List<Gallery.Users.UserRef> userRef;

        /**
         * Gets the value of the userRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the userRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUserRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Gallery.Users.UserRef }
         * 
         * 
         */
        public List<Gallery.Users.UserRef> getUserRef() {
            if (userRef == null) {
                userRef = new ArrayList<Gallery.Users.UserRef>();
            }
            return this.userRef;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="emailAddress" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class UserRef {

            @XmlAttribute(name = "emailAddress")
            protected String emailAddress;

            /**
             * Gets the value of the emailAddress property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEmailAddress() {
                return emailAddress;
            }

            /**
             * Sets the value of the emailAddress property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEmailAddress(String value) {
                this.emailAddress = value;
            }

        }

    }

}
