//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.10 at 09:35:55 AM BST 
//


package walla.datatypes.auto;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the walla.datatypes.auto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: walla.datatypes.auto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CategoryList }
     * 
     */
    public CategoryList createCategoryList() {
        return new CategoryList();
    }

    /**
     * Create an instance of {@link Gallery }
     * 
     */
    public Gallery createGallery() {
        return new Gallery();
    }

    /**
     * Create an instance of {@link GalleryList }
     * 
     */
    public GalleryList createGalleryList() {
        return new GalleryList();
    }

    /**
     * Create an instance of {@link GalleryOptions }
     * 
     */
    public GalleryOptions createGalleryOptions() {
        return new GalleryOptions();
    }

    /**
     * Create an instance of {@link ImageList }
     * 
     */
    public ImageList createImageList() {
        return new ImageList();
    }

    /**
     * Create an instance of {@link ImageMeta }
     * 
     */
    public ImageMeta createImageMeta() {
        return new ImageMeta();
    }

    /**
     * Create an instance of {@link TagList }
     * 
     */
    public TagList createTagList() {
        return new TagList();
    }

    /**
     * Create an instance of {@link UploadStatusList }
     * 
     */
    public UploadStatusList createUploadStatusList() {
        return new UploadStatusList();
    }

    /**
     * Create an instance of {@link ImageMeta.Tags }
     * 
     */
    public ImageMeta.Tags createImageMetaTags() {
        return new ImageMeta.Tags();
    }

    /**
     * Create an instance of {@link ImageList.Images }
     * 
     */
    public ImageList.Images createImageListImages() {
        return new ImageList.Images();
    }

    /**
     * Create an instance of {@link GalleryOptions.Style }
     * 
     */
    public GalleryOptions.Style createGalleryOptionsStyle() {
        return new GalleryOptions.Style();
    }

    /**
     * Create an instance of {@link GalleryOptions.Presentation }
     * 
     */
    public GalleryOptions.Presentation createGalleryOptionsPresentation() {
        return new GalleryOptions.Presentation();
    }

    /**
     * Create an instance of {@link GalleryList.GalleryRef }
     * 
     */
    public GalleryList.GalleryRef createGalleryListGalleryRef() {
        return new GalleryList.GalleryRef();
    }

    /**
     * Create an instance of {@link Gallery.Sections }
     * 
     */
    public Gallery.Sections createGallerySections() {
        return new Gallery.Sections();
    }

    /**
     * Create an instance of {@link Gallery.Sorts }
     * 
     */
    public Gallery.Sorts createGallerySorts() {
        return new Gallery.Sorts();
    }

    /**
     * Create an instance of {@link Gallery.Tags }
     * 
     */
    public Gallery.Tags createGalleryTags() {
        return new Gallery.Tags();
    }

    /**
     * Create an instance of {@link Gallery.Categories }
     * 
     */
    public Gallery.Categories createGalleryCategories() {
        return new Gallery.Categories();
    }

    /**
     * Create an instance of {@link Gallery.Users }
     * 
     */
    public Gallery.Users createGalleryUsers() {
        return new Gallery.Users();
    }

    /**
     * Create an instance of {@link Account }
     * 
     */
    public Account createAccount() {
        return new Account();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link CategoryList.CategoryRef }
     * 
     */
    public CategoryList.CategoryRef createCategoryListCategoryRef() {
        return new CategoryList.CategoryRef();
    }

    /**
     * Create an instance of {@link ClientApp }
     * 
     */
    public ClientApp createClientApp() {
        return new ClientApp();
    }

    /**
     * Create an instance of {@link ImageIdList }
     * 
     */
    public ImageIdList createImageIdList() {
        return new ImageIdList();
    }

    /**
     * Create an instance of {@link Logon }
     * 
     */
    public Logon createLogon() {
        return new Logon();
    }

    /**
     * Create an instance of {@link UserApp }
     * 
     */
    public UserApp createUserApp() {
        return new UserApp();
    }

    /**
     * Create an instance of {@link UserApp555 }
     * 
     */
    public UserApp555 createUserApp555() {
        return new UserApp555();
    }

    /**
     * Create an instance of {@link Tag }
     * 
     */
    public Tag createTag() {
        return new Tag();
    }

    /**
     * Create an instance of {@link TagList.TagRef }
     * 
     */
    public TagList.TagRef createTagListTagRef() {
        return new TagList.TagRef();
    }

    /**
     * Create an instance of {@link UploadStatusList.ImageUploadRef }
     * 
     */
    public UploadStatusList.ImageUploadRef createUploadStatusListImageUploadRef() {
        return new UploadStatusList.ImageUploadRef();
    }

    /**
     * Create an instance of {@link ImageMeta.Tags.TagRef }
     * 
     */
    public ImageMeta.Tags.TagRef createImageMetaTagsTagRef() {
        return new ImageMeta.Tags.TagRef();
    }

    /**
     * Create an instance of {@link ImageList.Images.ImageRef }
     * 
     */
    public ImageList.Images.ImageRef createImageListImagesImageRef() {
        return new ImageList.Images.ImageRef();
    }

    /**
     * Create an instance of {@link GalleryOptions.Style.StyleRef }
     * 
     */
    public GalleryOptions.Style.StyleRef createGalleryOptionsStyleStyleRef() {
        return new GalleryOptions.Style.StyleRef();
    }

    /**
     * Create an instance of {@link GalleryOptions.Presentation.PresentationRef }
     * 
     */
    public GalleryOptions.Presentation.PresentationRef createGalleryOptionsPresentationPresentationRef() {
        return new GalleryOptions.Presentation.PresentationRef();
    }

    /**
     * Create an instance of {@link GalleryList.GalleryRef.SectionRef }
     * 
     */
    public GalleryList.GalleryRef.SectionRef createGalleryListGalleryRefSectionRef() {
        return new GalleryList.GalleryRef.SectionRef();
    }

    /**
     * Create an instance of {@link Gallery.Sections.SectionRef }
     * 
     */
    public Gallery.Sections.SectionRef createGallerySectionsSectionRef() {
        return new Gallery.Sections.SectionRef();
    }

    /**
     * Create an instance of {@link Gallery.Sorts.SortRef }
     * 
     */
    public Gallery.Sorts.SortRef createGallerySortsSortRef() {
        return new Gallery.Sorts.SortRef();
    }

    /**
     * Create an instance of {@link Gallery.Tags.TagRef }
     * 
     */
    public Gallery.Tags.TagRef createGalleryTagsTagRef() {
        return new Gallery.Tags.TagRef();
    }

    /**
     * Create an instance of {@link Gallery.Categories.CategoryRef }
     * 
     */
    public Gallery.Categories.CategoryRef createGalleryCategoriesCategoryRef() {
        return new Gallery.Categories.CategoryRef();
    }

    /**
     * Create an instance of {@link Gallery.Users.UserRef }
     * 
     */
    public Gallery.Users.UserRef createGalleryUsersUserRef() {
        return new Gallery.Users.UserRef();
    }

}
